    #ifndef _REGISTER_LOGON_MODULE_H_
#define _REGISTER_LOGON_MODULE_H_


#define EmpiricalOfValueOfUpgrade(n) n*100;


#define POINT_OF_DOCTOR_BRAINS          7
#define POINT_OF_DOCTOR_PHYSICAL        3
#define POINT_OF_DOCTOR_ROOTBONE      6    
#define POINT_OF_DOCTOR_SPIRIT              4
#define POINT_OF_DOCTOR_AGILITY             5
 
#define POINT_OF_MASTER_BRAINS           7
#define POINT_OF_MASTER_PHYSICAL        3
#define POINT_OF_MASTER_ROOTBONE       5
#define POINT_OF_MASTER_SPIRIT              5
#define POINT_OF_MASTER_AGILITY             5

#define POINT_OF_KNIGHT_BRAINS           6
#define POINT_OF_KNIGHT_PHYSICAL        4
#define POINT_OF_KNIGHT_ROOTBONE       5
#define POINT_OF_KNIGHT_SPIRIT              5
#define POINT_OF_KNIGHT_AGILITY             5

#define POINT_OF_WARRIOR_BRAINS             5
#define POINT_OF_WARRIOR_PHYSICAL          5
#define POINT_OF_WARRIOR_ROOTBONE        7
#define POINT_OF_WARRIOR_SPIRIT              3
#define POINT_OF_WARRIOR_AGILITY            5

#define POINT_OF_SHOOTER_BRAINS          3
#define POINT_OF_SHOOTER_PHYSICAL       7   
#define POINT_OF_SHOOTER_ROOTBONE      5
#define POINT_OF_SHOOTER_SPIRIT             5
#define POINT_OF_SHOOTER_AGILITY            5


#define BASE_EXTEND_TRANSITION_DOCTOR_MATTACK(x) x*10
#define BASE_EXTEND_TRANSITION_DOCTOR_PATTACK(x)  x*7
#define BASE_EXTEND_TRANSITION_DOCTOR_MDEFENSE(x) x*4
#define BASE_EXTEND_TRANSITION_DOCTOR_PDEFENSE(x) x*4
#define BASE_EXTEND_TRANSITION_DOCTOR_AGILITY(x)    x*1
#define BASE_EXTEND_TRANSITION_DOCTOR_ALLBLOOD(x) x*15
#define BASE_EXTEND_TRANSITION_DOCTOR_ALLMAGIC(x) x*18
#define BASE_EXTEND_TRANSITION_DOCTOR_DEADLY(x)     x*0
  
#define BASE_EXTEND_TRANSITION_MASTER_MATTACK(x) x*11
#define BASE_EXTEND_TRANSITION_MASTER_PATTACK(x) x*8
#define BASE_EXTEND_TRANSITION_MASTER_MDEFENSE(x) x*3
#define BASE_EXTEND_TRANSITION_MASTER_PDEFENSE(x) x*3
#define BASE_EXTEND_TRANSITION_MASTER_AGILITY(x)    x*1
#define BASE_EXTEND_TRANSITION_MASTER_ALLBLOOD(x) x*12
#define BASE_EXTEND_TRANSITION_MASTER_ALLMAGIC(x) x*15
#define BASE_EXTEND_TRANSITION_MASTER_DEADLY(x)     x*0

#define BASE_EXTEND_TRANSITION_KNIGHT_MATTACK(x) x*8
#define BASE_EXTEND_TRANSITION_KNIGHT_PATTACK(x) x*6
#define BASE_EXTEND_TRANSITION_KNIGHT_MDEFENSE(x) x*4
#define BASE_EXTEND_TRANSITION_KNIGHT_PDEFENSE(x) x*4
#define BASE_EXTEND_TRANSITION_KNIGHT_AGILITY(x)    x*1
#define BASE_EXTEND_TRANSITION_KNIGHT_ALLBLOOD(x) x*15
#define BASE_EXTEND_TRANSITION_KNIGHT_ALLMAGIC(x) x*15
#define BASE_EXTEND_TRANSITION_KNIGHT_DEADLY(x)     x*0

#define BASE_EXTEND_TRANSITION_WARRIOR_MATTACK(x) x*5
#define BASE_EXTEND_TRANSITION_WARRIOR_PATTACK(x) x*8
#define BASE_EXTEND_TRANSITION_WARRIOR_MDEFENSE(x) x*8
#define BASE_EXTEND_TRANSITION_WARRIOR_PDEFENSE(x) x*8
#define BASE_EXTEND_TRANSITION_WARRIOR_AGILITY(x)   x*1
#define BASE_EXTEND_TRANSITION_WARRIOR_ALLBLOOD(x) x*0
#define BASE_EXTEND_TRANSITION_WARRIOR_ALLMAGIC(x) x*12
#define BASE_EXTEND_TRANSITION_WARRIOR_DEADLY(x)    x*0

#define BASE_EXTEND_TRANSITION_SHOOTER_MATTACK(x) x*7
#define BASE_EXTEND_TRANSITION_SHOOTER_PATTACK(x) x*10
#define BASE_EXTEND_TRANSITION_SHOOTER_MDEFENSE(x) x*4
#define BASE_EXTEND_TRANSITION_SHOOTER_PDEFENSE(x) x*4
#define BASE_EXTEND_TRANSITION_SHOOTER_AGILITY(x)   x*1
#define BASE_EXTEND_TRANSITION_SHOOTER_ALLBLOOD(x) x*16
#define BASE_EXTEND_TRANSITION_SHOOTER_ALLMAGIC(x) x*15
#define BASE_EXTEND_TRANSITION_SHOOTER_DEADLY(x)    x*0


void RL_RegisterOrLogon_Close();

#endif